<a href="https://colab.research.google.com/github/ashish-3916/machine-learning-/blob/main/feature_scaling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn import preprocessing

In [3]:
X = np.array ([
               [1., -1., 2,],
               [2.,  0., 0,],
               [0.,  1.,-1,] ])
  # row -> datapoints 
  # col -> features

In [12]:
X_scaled = preprocessing.scale(X) # make mean as 0 and variance as 0
X_scaled

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [7]:
X_scaled.mean(axis=0)  # mean of every feature is 0

array([0., 0., 0.])

In [10]:
X_scaled.std(axis=0)  # variance of every feature is 1


array([1., 1., 1.])

one thing we need to take notice is we have to do feature scaling combined on testing and training data , as if we do them separately then mean and other parameters would be differnet bcz of kind of data we have, so make sure we do feature scaling combined

---

but what if we don't have the testing data  ? Huh , how can me improve our featuring so it results are good with unknown training data  ?

---

when we scale our training data we store the parameters we scale them with and them use those parameters to unknown testing data too.

---

we have a function for that

In [18]:
scaler = preprocessing.StandardScaler() # we can pass parameters(mean , variance )# object
scaler.fit(X)  # store the paramters and also scale the testing data

scaler.transform(X) # transform any unknown data , say X  

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [19]:
# we can check that its the same

In [20]:
X_test = [[1 , 1, 0]]
scaler.transform(X_test)

array([[ 0.        ,  1.22474487, -0.26726124]])

In [21]:
# we have others scalers to (min_max_scaler  , standard)  checkout documentation